### ISSUE TITLE
MyBatis-Spring-Boot 1.1.1の適用

### ISSUE THREAD

**Issue by kazuki43zoo** [kazuki43zoo/spring-tx-timeout#3]
プロジェクトにMyBatis-Spring-Boot 1.1.1 を適用してください。
### 参考サイト
- http://qiita.com/kazuki43zoo/items/ea79e206d7c2e990e478

**Comment by ToshihiroTamura** [comment]
サイトを参考に導入しました

**Comment by kazuki43zoo** [comment]
:+1:
